let http = require('http')
let express = require('express')
let bodyParser = require('body-parser')
let cors = require('cors')
let morgan = require('morgan')
let {sequelize} = require('./models')
let config = require('./config/config')
let toolbox = require('./utils/Toolbox')
let socketServer = require('./SocketServer')
// let chatConstants = require('../../shared/chatConstants')

let app = express()
app.use(morgan('combined'))
app.use(bodyParser.json())
app.use(cors())

require('./passport')
require('./routes')(app)

sequelize.sync({force: false})
  .then(() => {
    let server = http.createServer(app)
    server.listen(config.port)
    socketServer.init(server)
    toolbox.logData(`Server started on port ${config.port}`)
  })
